### ISSUE TITLE
Improve regresison tests for content type ID operations in a list

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#1034]
The following functionality needs to be covered by regression tests. Both CSOM and SSOM tests must be implemented.

* [x] .AddContentTypeLink() should work with content type ID #1016
* [x] .RemoveContentTypeLink() should work with content type ID #1020
* [x] .HideContentTypeLink() should work with content type ID #1021
* [x] .AddUniqueContentTypeOrder() should work with content type ID #1022

**Comment by SubPointSupport** [comment]
In progress.

**Comment by SubPointSupport** [comment]
Added new test to cover "add content type to list, by ID/Name":
* CanDeploy_CanAddContentTypeLinksInList_ById
* CanDeploy_CanAddContentTypeLinksInList_ByName
