### ISSUE TITLE
Migrate regression testing  Win2016, SP2016 and VS2015 platform

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#1096]
SPMeta2 regression testing should work well on updated platform under:
* Win2016
* SP2016 
* VS2016

Both local and distributed NCrunch-based testing should pass without major issues. This needs to be done in order to continue work on new features and releases. 

[x] **Configuration**
* [x] PS/DSC - initial module bootstrap, logging
* [x]  CSOM/SSOM Taxonomy Service app setup: - This service application is the default storage location for column specific term sets, required for taxonomy related testing
* [x] investigate initial PS/CSOM 404 error, should work straight away
>  https://github.com/PowerShell/SharePointDsc/issues/707
> https://github.com/SubPointSolutions/metabox/issues/55
* [x] CSOM creds are required for incremental provision testing (storage)
* [x] Initial domain user/groups for user-security related testing 
* [x] SSOM User profile app proxy, required by CoreProperty tests  ( https://github.com/SubPointSolutions/metabox/issues/59)
* [x] audience provision fail (user profile service isn't available) ( https://github.com/SubPointSolutions/metabox/issues/59)
* [x] SSOM User Profile service setup for audience provision test (No User Profile Service is available i the current context)  https://github.com/SubPointSolutions/metabox/issues/59)
* [x] CSOM/SSOM - Solution Sandbox service should be up (required by various tests) 
* [x] dependency on the domain name (users / groups)

[x] **NCrunch**
* [x] NCrunch setup (x64 as a build platform, default timeout update)

[x] **YAML changes**
* [x] extract credential information from YAML, all should be passed via CMD or already set in ENV variables
* [x] removfe YAML, use PowerShell instead

[x] **SP2016 issues / failed tests**
* [x] CanDeploy_XsltListViewWebPart_ByListId, propery validation
* [x] CSOM - Random fails on CanDeployRandom_UserDefinition, can't find existing user
* [x] SSOM - CanDeploy_WebPartPage -> PageLayoutTemplate: [1] is not supported (https://github.com/SubPointSolutions/spmeta2/issues/1102)
* [x] CSOM/SSOM - CanDeploy_TaxonomyTermStoryById/Name (taxonomy service setup)
* [x] SSOM - CanDeploy_LookupField_With_CountRelated 

[x] **Internal setups**
* [x] ExpectUpdateAsWebPartPageLayoutTemplateService - https://github.com/SubPointSolutions/spmeta2/issues/1102

[x] **Further iteration**
* [x] discussion item / reply-item tests fail
* [ ] SPMeta2.Containers.AppContainer project build (old asp.net or sometihng)
* [ ] SubPointSolutions.Docs project build
* [ ] content type hub related setup
* [ ] should not run as system account for app provision testing
* [ ] Workflow Manager 2013 setup (metabox offload - https://github.com/SubPointSolutions/metabox/issues/6)
* [ ] Language packs  (metabox offload - https://github.com/SubPointSolutions/metabox/issues/57)
* [ ] CSOM - CanDeploy_ListViewWebPart_As_Calender_With_DateRangesOverlap, View binding
* [ ] CSOM - CanDeploy_ContentTypeFieldLink_WithProperties, 
>  Microsoft.SharePoint.Client.ServerException: Field or property "DisplayName" does not exist.
* [ ] CSOM, CanDeploy_XsltListViewWebPart_Prop_InplaceSearchEnabled

A follow up on the following task:
> Migrate solution to VS2015/VS2017 #1043

**Comment by SubPointSupport** [comment]
Few day delay due to SharePoint 2016 install issue. Could not point this one early:
> https://github.com/SubPointSolutions/metabox/issues/55

Current progress with regression:
* [x] SP2016 CSOM
* [x] O355 CSOM (we need to separate emails/user logins for O365 testing)
* [ ] SP2016 SSOM - in progress

Overal shape of the SP2016 regression is promsing, dev branch looks stable. However some features seem to regress - various edge cases on web parts for both SP2016 and O365.

SSOM testing is about to finish, day-two to push new release to NuGet.

**Comment by andreasblueher** [comment]
Keep up the good work guys!

**Comment by SubPointSupport** [comment]
`dev` branch is super-stable; CSOM/SSOM regression against 2016, O365 against several random tenants.

Minor work to fix up seriallization/hash API for @netarrow, and then building/pushing to NuGet
> Serialization error using ClientValueObject in AddListItem using IncrementalDeploy #1100
