### ISSUE TITLE
SPMeta2 v1.3.0 specification

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/spmeta2#757]
Current ticket describes some nice feature we would like to see in SPMeta2 1.3.0. More of an idea aggregation, gathering and discussion place aiming to reduce amount of tickets created without well-defined scope.

The following are the high level specs for the SPMeta2 1.3.0 - the features, improvements and potential directions. The spec and feature set is open for discussion and will be refined over time.

## [DONE] Native NuGet support
* [x] STATE: already implemented as a part of separate [MetaPack API](https://github.com/SubPointSolutions/MetaPack)

SPMeta2 should support packaging models into NuGet packages
- NuGet packages packaging, publishing
- Models orchestrations - which model should be deployed, the sequence 

The main goal is to provide a NuGet transport for both developers (VS) and IT-pros so that the M2 based models can be easily shared, published, reused, updated and distributed.

## [TODO] Model parameters
* [ ] STATE: to be implemented - Introduce model parameters support #1004

All definition properties are to be changed to custom classes. The goal is to provide an ability to set "calculable / replaceable / reusable" parameters across the model. For instance, Fields / Content Type groups is a string. It be nice to define a StringParameter once, use it as a group and then have ab ability to change it consistently across the model - both in runtime or after deserialization.

Implicit operator and casting in c# allows to create custom classes which can be casted to simple types - string, int, doubles, enums. So that the following syntax would be supported:

```
 var def = new FieldDefinition();

def.Group = "Custom Feilds";
def.Group = new StringParameter("Fields Group Name", "Custom Fields");
```

The ultimate goal is to persist parameter over the serialization/deserialization, so that deserialized models can be parametrized again. On the other hand, the C#/API should work smoothly as well.

## [TODO] String typing for the definition enums
* [ ] STATE: in review

Lots of definition props are strings, but should have been enums. Most of the BuiltInXXX classes should be migrated from string values to enums.

## [DONE] Incremental provision support
* [x] STATE: already implemented
Implement 'incremental' provision support #553
https://github.com/SubPointSolutions/spmeta2/issues/553

SPMeta2 should be able to calculate the different in the models skipping things that should not be updated and focusing only on the changes / new things.

## [TODO] Parallel provision  support
Some artefacts can be deployed in the separate threads. For instance webs, lists - all these can be paralleled. M2 should support that at the syntax level. The implementation should be pluggable.

## [DONE] Reverse engineering for the existing SharePoint sites
* [x] STATE: already implemented

Implemented as a part of SPMeta2-Reverse project - https://github.com/SubPointSolutions/spmeta2-reverse

SPMeta2 should support building models out of the existing SharePoint sites. A separate API is to be created, full regression testing should be done. 

## [TODO] Implement more PreDeployment services
* [ ] STATE: in review

SPMeta2 has a concept of "pre-deployment/post-deployment" services which are called before/after artifact provision. There is a desire to have built-in services to provide common tasks around validation such as:
* Implement 'RequireSandboxSolutionServiceDeploymentService' #639
* Implement 'RequireWebFeatureDeploymentService' #564
* Implement 'RequireSiteFeatureDeploymentService' #563
* Implement 'RequireSearchServiceApplicationAdminAccessDeploymentService' #551
* Implement 'RequireSharePointEditionDeploymentService' #452
* Implement 'RequireSiteTemplateDeploymentService' #439
* Implement 'RequireOWADeploymentService' #400
* Implement 'RequireSP2013WorkflowDeploymentService' #399
* Implement 'RequireFeatureDeploymentService' #398
* Implement 'RequireMMSAdminAccessDeploymentService' #397
* Implement 'RequireSPFarmVersionDeploymentService' #396
* Implement 'DefaultSiteBackupPreDeploymentService' #339

All these issues are marked as closed but weren't implemented yet. Aggregated under "nice-to-have" milestone for the time being.

**Comment by SubPointSupport** [comment]
cc @andreasblueher, @adaoust, @sergeisnitko, @rolandoldengarm just FYI as you were reporting most of the highlighted features. Let us know if there is anything important we need to consider for the next major version upgrade.
